accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('emaillogin/', views.email_login, name='email_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
]

students/urls.py
from django.shortcuts import redirect
from django.urls import path
from . import views

app_name = 'students'
urlpatterns = [
    path('', lambda req: redirect('/home/')),
    path('student/update/<int:pk>/', views.StudentUpdateView.as_view(), name='student_update'),
    path('student/delete/<int:pk>/', views.StudentDeleteView.as_view(), name='student_delete'),
    path('group/add/', views.GroupCreateView.as_view(), name='group_create'),
    path('student/add/', views.StudentCreateView.as_view(), name='student_create'),
    path('home/', views.GroupListView.as_view(), name='group_list'),
    path('group/<slug:slug>/', views.GroupDetailView.as_view(), name='group_detail'),
    path('student/<str:fio>/', views.StudentDetailView.as_view(), name='student_detail'),
    path('group/update/<slug:slug>/', views.GroupUpdateView.as_view(), name='group_update'),
    path('group/delete/<slug:slug>/', views.GroupDeleteView.as_view(), name='group_delete'),
]

students_base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('account/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('students.urls', namespace='students')),
]

students/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.text import slugify
from django.db.models.signals import post_init, post_save, post_delete
from django.dispatch import receiver
from datetime import datetime


class Info_About_Models(models.Model):
    model_name = models.CharField(max_length=255, blank=True)
    model_create = models.CharField(max_length=255, blank=True)
    model_editing = models.CharField(max_length=255, blank=True)
    model_delete = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.model_name


class Group(models.Model):
    title = models.CharField(max_length=20)
    group_leader = models.ForeignKey('Student', null=True, blank=True, related_name='group_leader',
                                     on_delete=models.DO_NOTHING)
    slug = models.SlugField(max_length=20, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Group, self).save(*args, **kwargs)

    class Meta:
        ordering = ('title',)
        verbose_name = 'group'
        verbose_name_plural = 'groups'

    def get_absolute_url(self):
        return reverse('students:group_detail', args=[self.slug])

    def __str__(self):
        return self.title


class Student(models.Model):
    fio = models.CharField(max_length=100)
    birth_date = models.DateField()
    student_ticket = models.IntegerField()
    group = models.ForeignKey(Group, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ('fio', 'group')
        verbose_name = 'student'
        verbose_name_plural = 'students'

    def __str__(self):
        return self.fio

    def get_absolute_url(self):
        return reverse('students:student_detail', args=[self.fio])


'''

@receiver(post_init, sender=Student)  # создание новой записи (модель Students)
def post_init_students(instance, **kwargs):
    i_a_m = Info_About_Models.objects.get_or_create(model_name='Student', model_create=datetime.now())

'''


@receiver(post_save, sender=Student)  # редактирование записи (модель Students)
def post_save_students(instance, **kwargs):
    i_a_m = Info_About_Models.objects.get_or_create(model_name='Student', model_editing=datetime.now())


@receiver(post_delete, sender=Student)  # удаление записи (модель Students)
def post_delete_students(instance, **kwargs):
    i_a_m = Info_About_Models.objects.get_or_create(model_name='Student', model_delete=datetime.now())


'''
@receiver(post_init, sender=Group)  # создание новой записи (модель Groups)
def post_init_groups(instance, **kwargs):
    i_a_m = Info_About_Models.objects.get_or_create(model_name='Group', model_create=datetime.now())
'''


@receiver(post_save, sender=Group)  # редактирование записи (модель Groups)
def post_save_groups(instance, **kwargs):
    i_a_m = Info_About_Models.objects.get_or_create(model_name='Group', model_editing=datetime.now())


@receiver(post_delete, sender=Group)  # удаление записи (модель Groups)
def post_delete_groups(instance, **kwargs):
    i_a_m = Info_About_Models.objects.get_or_create(model_name='Group')

students/forms.py
from django import forms
from students.models import Group, Student


class GroupForm(forms.ModelForm):
    title = forms.CharField(label='Title of group', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter a group title'
    }))
    group_leader = forms.ModelChoiceField(
        label='Group leader', queryset=Student.objects.all(), widget=forms.Select(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = Group
        fields = 'title', 'group_leader'


class StudentForm(forms.ModelForm):
    fio = forms.CharField(label='Name, Surname', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter a full name and surname'
    }))
    birth_date = forms.DateField(label='Day of birth')
    student_ticket = forms.IntegerField(label="Student's ticket")
    group = forms.ModelChoiceField(
        label='Group', queryset=Group.objects.all(), widget=forms.Select(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = Student
        fields = '__all__'

students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.base import View
from django.db.models import Count
from django.db import connection
from students.forms import GroupForm, StudentForm
from students.models import Group, Student


class GroupListView(ListView):
    def get(self, request, ordering='AZ', *args, **kwargs):
        group_list = Group.objects.all()
        group_list = Group.objects.annotate(nstud=Count('student'))
        template_name = 'group_list.html'
        context = {'group_list': group_list}
        return render(request, template_name, context)


class GroupDetailView(View):
    def get(self, request, ordering='AZ', *args, **kwargs):
        group = Group.objects.get(slug=self.kwargs['slug'])
        students = Student.objects.filter(group=group).order_by('fio')
        template_name = 'group_detail.html'
        context = {'group': group, 'students': students}
        return render(request, template_name, context)


class StudentDetailView(View):
    def get(self, request, ordering='AZ', *args, **kwargs):
        student = Student.objects.get(fio=self.kwargs['fio'])
        template_name = 'student_detail.html'
        context = {'student': student}
        return render(request, template_name, context)


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupForm
    template_name = 'groups/create.html'
    success_url = reverse_lazy('students:group_list')


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupForm
    template_name = 'groups/update.html'
    success_url = reverse_lazy('students:group_list')


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('students:group_list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class StudentCreateView(LoginRequiredMixin, CreateView):
    model = Student
    form_class = StudentForm
    template_name = 'students/create.html'
    success_url = reverse_lazy('students:group_list')


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = StudentForm
    template_name = 'students/update.html'
    success_url = reverse_lazy('students:group_list')


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy('students:group_list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

students/templates/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light container" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'students:group_list' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</nav>
<nav class="navbar navbar-expand-lg navbar-light container" style="background-color: #e3f2fd;">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

            {% if user.is_authenticated %}
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'accounts: logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'email_login' %}">Login with Email</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Registration</a>
                </li>
            {% endif %}

        </ul>
    </div>

</nav>
<div class="container">

</div>
<div class="container">
    {% block content %}{% endblock %}
</div>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
<script>
    $(document).ready(function () {
        $('.js-example-basic-single').select2();
        $('.js-example-basic-multiple').select2();
    });
</script>
</body>
</html>

students/templates/form.html
<div class="row">
    <div class="col-md-4">
        <form action="{{action}}" method="post"> {% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="btn btn-primary"> {{ button }}</button>
        </form>
    </div>
</div>

students/templates/group_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>Students of {{ group.title }} group:</h2>
    {% for student in students %}
        <tr>
            <td>
                <a href="{{ student.get_absolute_url }} ">{{ student.fio }}</a>
            </td>
            {% if user.is_authenticated %}
                <td>
                    <a href="{% url 'students:student_update' student.pk %}">
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </a></td>
                <td>
                    <a href="{% url 'students:student_delete' student.pk %}">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </a>
                </td>
            {% else %}
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            {% endif %}
        </tr>
        <br>
    {% endfor %}
    {% if user.is_authenticated %}
        <a href="{% url 'students:student_create' %}">
    {% endif %}
<button type="submit" class="btn btn-primary">Create new student</button>
</a>
{% endblock %}

students/templates/group_list.html
{% extends 'base.html' %}
{% block title %}List of groups{% endblock %}

{% block content %}
    <h1>List of groups</h1>
    <div class="row ">
        <div class="col-md-8 mx-auto my-2">
            <table class="table table-striped">
                <tr>
                    <th>Title</th>
                    <th>Number of students</th>
                    <th>Group leader</th>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>

                </tr>
                {% for group in group_list %}
                    <tr>
                        <td>
                            <a href="{{ group.get_absolute_url }} ">{{ group.title }}</a>
                        </td>
                        <td>{{ group.nstud }}</td>
                        <td>{{ group.group_leader }}</td>
                        {% if user.is_authenticated %}
                            <td>
                                <a href="{% url 'students:group_update' group.slug %}">
                                    <button type="submit" class="btn btn-primary">Edit</button>
                                </a></td>
                            <td>
                                <a href="{% url 'students:group_delete' group.slug %}">
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </a>
                            </td>
                        {% else %}
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        {% endif %}
                    </tr>


                {% endfor %}
            </table>
            {% if user.is_authenticated %}
                <a href="{% url 'students:group_create' %}">
            {% endif %}
            <button type="submit" class="btn btn-primary">Create new group</button>
            </a>
        </div>
    </div>



{% endblock %}

students/templates/student_detail.html
{% extends "base.html" %}
{% load students_tags %}
{% block content %}
    <h2>Page of student {{ student.fio }}</h2>
    Student's ticket: {{ student.student_ticket }}
    <br>
    Date of birth: {{ student.birth_date }}
    <br>
    Student's group: {{ student.group }}
    <br>
    {% edit user.username %}
{% endblock %}